pipeline:
  buildphp:
    image: plugins/docker
    registry: registry.dryusdan.fr
    build_args: PHP_VER=7.1.12
    tags:
      - 7.1
    dockerfile: https://github.com/xataz/docker-nginx-php.git
    repo: registry.dryusdan.fr/dryusdan/php
    secrets: [ docker_username, docker_password ]

  build:
    image: plugins/docker
    registry: registry.dryusdan.fr
    repo: registry.dryusdan.fr/dryusdan/cachethq
    secrets: [ docker_username, docker_password ]

  push:
    image: appleboy/drone-git-push
    branch: master
    remote: git@github.com:Dryusdan/docker-cachethq.git
    secrets: [ git_push_ssh_key ]
