pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk --update add docker
      - "export DOCKER_HOST=unix:///var/run/host.sock"
      - docker build -t registry.dryusdan.fr/dryusdan/cachethq .
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro
      - /home/docker/.docker:/docker/.docker/
  
  push:
    image: alpine:3.6
    commands:
      - apk --update add docker
      - "export DOCKER_HOST=unix:///var/run/host.sock"
      - docker login -u `cat /docker/.docker/username-perso`  -p `cat /docker/.docker/password-perso` registry.dryusdan.fr
      - docker push registry.dryusdan.fr/dryusdan/cachethq
      - docker login -u `cat /docker/.docker/username`  -p `cat /docker/.docker/password`
      - docker push dryusdan/cachethq
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro
      - /home/docker/.docker:/docker/.docker/

