pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk --update add docker
      - "export DOCKER_HOST=unix:///var/run/host.sock"
      - docker login -u `cat /docker/.docker/username`  -p `cat /docker/.docker/password` registry.dryusdan.fr
      - docker build -t registry.dryusdan.fr/dryusdan/cachethq .
      - docker push registry.dryusdan.fr/dryusdan/cachethq
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro
      - /home/docker/.docker/config.json:/docker/.docker/config.json:ro
  
  push:
    image: alpine:3.6
    commands:
      - apk --update add docker
      - "export DOCKER_HOST=unix:///var/run/host.sock"
      - docker images
      - docker login -u `cat /docker/.docker/username`  -p `cat /docker/.docker/password` registry.dryusdan.fr
      - docker push registry.dryusdan.fr/dryusdan/cachethq
    volumes:
      - /var/run/docker.sock:/var/run/host.sock:ro
      - /home/docker/.docker/config.json:/docker/.docker/config.json:ro

