pipeline:
  build:
    image: plugins/docker
    repo: registry.dryusdan.fr/dryusdan/cachethq
    registry: registry.dryusdan.fr
    username: $$PRIVATE_LOGIN
    password: $$PRIVATE_PASSWORD
    action: build
    tags: 
      - latest
    when:
      branch: master
      event: [push, tag, deployment]
